services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: ywimc
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  application:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: "jdbc:postgresql://database:5432/ywimc"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
      JWT_SECRET: "12345678"
      JWT_ISSUER: "dev"
    depends_on:
      - database